parameters:
  name: 'Build'
  dependsOn: ''
  pool: Storm-Build-Production
jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  dependsOn: ${{ parameters.dependsOn }}
  variables:
    cake.buildTarget: 'CI'
    build.configuration: 'Release'
    cake.verbosity: 'Normal'
  steps:
  - powershell: ./build.ps1 -Target "$(cake.buildTarget)" -Configuration "$(build.configuration)" -Verbosity "$(cake.verbosity)"
    displayName: 'Cake Build'
  - powershell: Write-Host '##vso[build.addbuildtag]PR'
    displayName: 'Mark as PR Build'
    condition: and(succeeded(), in(variables['Build.Reason'], 'PullRequest'))
  - powershell: Write-Host '##vso[build.addbuildtag]Release'
    displayName: 'Mark as Release Build'
    condition: and(and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI')), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
